### ISSUE TITLE
errors in compiling FVCOM-FABM

### ISSUE THREAD

**Issue by jayzhong2022** [UK-FVCOM-Usergroup/uk-fvcom#13]
Hi, I am a young marine researcher in China. Thanks for your FVCOM-FABM code. Befor compiling FVCOM-FABM code, I have built fvcom and ERSEM with fabm-1.0.1 by using cmake. But when I uncomment "FLAG_25 -DFABM" in make.inc, some errors appearred. So it maybe was caused by what? the version of fabm? Thank you very much.
![erro](https://user-images.githubusercontent.com/118873290/203686256-a33db537-8d83-4e9c-b8e5-c83c60782817.png)

**Comment by mikebedington** [comment]
Sorry just stumbled over this too. It seems to only occur with certain intel compilers - I'm just seeing if I can work out how to fix it

**Comment by mikebedington** [comment]
Ok so I got through this error by passing a declaration to turn off argument checking
!DEC$ ATTRIBUTES NO_ARG_CHECK :: pdata_hz

But there are still errors from the compiler I haven't managed to fix, it seems to be struggling with type checking in general. In particular it is struggling with type determined subroutines which it doesn't seem a fan of:

e.g.
mod_fabm_3D.f90(192): error #8486: There is no matching specific subroutine for this type bound generic subroutine call.   [LINK_HORIZONTAL_DATA]
call model%link_horizontal_data(fabm_standard_variables%surface_downwelling_shortwave_flux,SWRAD_WATTS(1:M))

Also turning off argument checking then causes a further error for some variables e.g. 
mod_fabm_3D.f90(241): error #6409: This name has already been used as an external procedure name.   [FABM_ALL_BT]
ALLOCATE(FABM_ALL_BT(0:MT,size(model%bottom_state_variables)));  FABM_ALL_BT =  0.001_SP
Though I think that error is misleading as even changing to a variable name which definitely doesn't occur elsewhere it pings the same error

I've tried replacing them with variables of explicit type, calling the specific subroutines, and fiddling the imports with no progress. Any clever ideas @riquitorres or @jornbr?

I'm assuming its a compiler bug to work around as it compiles fine with other compilers. There seems to have been a problem with  older versions but appears it should be solved by now (I'm using 2022 intel compilers):
https://community.intel.com/t5/Intel-Fortran-Compiler/bug-problem-with-type-bound-generic-functions/m-p/775971

There are also some subtleties I haven't yet got my head around which might be the way we define the variables in FVCOM but I think this would have been picked up by other compiilers:
https://community.intel.com/t5/Intel-Fortran-Compiler/Problem-with-generic-type-bound-procedure-of-an-abstract-type/m-p/985009

**Comment by jornbr** [comment]
To get a clearer error message for the `link_horizontal_data` problem, I would temporarily replace `model%link_horizontal_data` with `model%link_horizontal_data_by_sn`. That way, you point it to a specific subroutine rather than a generic one, which will allow the compiler to say in more detail which arguments do not match, and why.  Or is that what you have done when you say "calling the specific subroutines"? I would expect the error message to become more specific this way... Disabling argument checking seems a bit dangerous and I have never seen that being necessary.

**Comment by mikebedington** [comment]
Thanks Jorn :-) Yep I had tried changing to the specific subroutine but I was doing it by variable not sn...

That changes the error to the same as the previous:
 error #6633: The type of the actual argument differs from the type of the dummy argument.   [SWRAD_WATTS]
So I guess its all the same issue with how we define the types in FVCOM vs what FABM is expecting and how intel interprets it?

E.g. in this case:
REAL(SP), ALLOCATABLE,TARGET :: SWRAD_WATTS(:)  !!SURFACE INCIDENT RADIATION
ALLOCATE(SWRAD_WATTS(0:MT))  ;SWRAD_WATTS  = ZERO !!SURFACE INCIDENT RADIATION

I agree disabling argument checking isn't ideal - my thinking was if its a compiler bug then maybe its acceptable but you're right should work it through before doing that.

**Comment by jornbr** [comment]
Hmm if the complaint is about `SWRAD_WATTS`, the typical reason would be that FABM was compiled with a different real kind than FVCOM (e.g., double vs single precision). Do you set [`FABM_REAL_KIND`](https://github.com/fabm-model/fabm/wiki/Building-and-installing#compilation-settings) when you build FABM, and if so, does that match FVCOM's `SP`?

**Comment by mikebedington** [comment]
No I didn't set the FABM precision when I built it, I'll have a go with that

**Comment by mikebedington** [comment]
Great yep thats fixed it! Thanks Jorn, I was running round in circles with that one - I definitely owe you a beer if you're ever over here :-) I'll tweak FVCOM so it stops you trying to compile with a different precision to FABM and gives a more sensible error message.

**Comment by jornbr** [comment]
Glad to hear it! I'll come and find you for that beer sometime :-)

**Comment by riquitorres** [comment]
I had nothing to do with it but I would love to have a beer with you too sometime soon!!
________________________________
